title: Hans5958's Website
description: Ready or not, here we go! Website of Hans5958.
baseurl: ""
url: https://hans5958.github.io

author: Hans5958
twitter: "@Hans5958"
copyright_year: 2021
repository: https://github.com/Hans5958/hans5958.github.io

markdown: kramdown
include: [".well-known"]
exclude: ["README.md", "CODE_OF_CONDUCT.md"]
